describe('template spec', () => {

    it('Register a user', () => {
      const randomEmail = Math.random().toString(36).substring(2, 15) + '@mail.com'
      const firstName = 'qa_test ' + Math.random().toString(36).substring(2, 7)
      const lastName = 'automate ' + Math.random().toString(36).substring(2, 7)
      cy.visit('https://automationexercise.com/')
      cy.contains(' Signup / Login')
        .should('be.visible')
        .click()
      cy.get('[data-qa="signup-name"]')
        .should('exist')
        .type('qa-test01')
      cy.get('[data-qa="signup-email"]')
        .should('exist')
        .type(randomEmail)
      cy.get('[data-qa="signup-button"]').click()
      cy.get('#id_gender2').click()
      cy.get('[data-qa="password"]')
        .type('122345678')
      cy.get('[data-qa="days"]').select('21')
      cy.get('[data-qa="months"]').select('July')
      cy.get('[data-qa="years"]').select('1998')
      cy.get('[data-qa="first_name"]')
        .should('exist')
        .type(firstName)
      cy.get('[data-qa="last_name"]')
        .should('exist')
        .type(lastName)
      cy.get('[data-qa="address"]')
        .should('exist')
        .type('address1')
      cy.get('[data-qa="country"]').select('Canada')
      cy.get('[data-qa="state"]')
        .should('exist')
        .type('state1')
      cy.get('[data-qa="city"]')
        .should('exist')
        .type('state1')
      cy.get('[data-qa="zipcode"]')
        .should('exist')
        .type('9000')
      cy.get('[data-qa="mobile_number"]')
        .should('exist')
        .type('+5555')
      cy.get('[data-qa="create-account"]').click()
      cy.url().should('include','/account_created')
      cy.contains('.title.text-center','Account Created!')
        .should('exist')
    })
  })